### ISSUE TITLE
[Story] Create Technical Architecture Document

### ISSUE THREAD

**Issue by colinalford** [colinalford/events#8]
## Description

As a developer, I want to understand how I can create features for this product so that I am in alignment with the technical architecture and the business constraints.

## Acceptance Criteria

Given I am a developer, when I look at the technical architecture documentation, I should understand how to create or modify features in the proposed structure.

## Task List
- [ ] Create blank document as Google Slides
- [ ] Create App Overview Section
- [ ] Create App Features Section
- [ ] Create Domain Security Section
- [ ] Create Domain Rules Section
- [ ] Create Logging Section
- [ ] Create Services/Communication Section
- [ ] Create Data Models Section
- [ ] Create Feature Components Section
- [ ] Create Shared Functionality Section

## Notes
* Follow template provided copied from [Dan Wahlin's Application Architecture Planning slides](https://docs.google.com/presentation/d/1cDD-v_A4j8o3JzNm0RVQ8R6oNZOE7meXIU4Dd44HyFU/edit?usp=sharing)
